name: Crypto Trading Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libfreetype6-dev \
          python3-dev \
          build-essential \
          wget

    - name: Install TA-Lib (optional)
      run: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib && ./configure && make && sudo make install

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install --use-pep517 --pre -r requirements.txt
        python -m nltk.downloader punkt vader_lexicon

    - name: Verify critical packages
      run: |
        python -c "import pandas as pd; print(f'\nPandas version: {pd.__version__}')"
        python -c "import pandas_ta; print(f'Pandas-TA version: {pandas_ta.__version__}')"
        python -c "import numpy as np; print(f'Numpy version: {np.__version__}')"

    - name: Run Trading Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py
