name: Crypto Analysis Bot
on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:        # Manual trigger enabled

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget autoconf automake libtool

      - name: Build TA-Lib from source
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          # Fix config files for Ubuntu 24.04 compatibility
          wget 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD' -O config.guess
          wget 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' -O config.sub
          ./configure --prefix=/usr
          make -j$(nproc)
          sudo make install
          sudo ldconfig
          cd ..
          rm -rf ta-lib ta-lib-0.4.0-src.tar.gz

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify TA-Lib installation
        run: python -c "import talib; print('TA-Lib version:', talib.__version__)"

      - name: Run Analysis Bot
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
