name: Crypto Analysis Bot
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install TA-Lib dependencies
        run: |
          # Add Ubuntu 22.04 (Jammy) repo temporarily (libta-lib-dev exists here)
          sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu jammy universe"
          sudo apt-get update
          sudo apt-get install -y libta-lib-dev
          # Remove the Jammy repo to avoid conflicts
          sudo rm /etc/apt/sources.list.d/archive_ubuntu_com_ubuntu_jammy_universe.list

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis Bot
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
