name: Run Python Script Every 30 Minutes
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Specify a compatible version (e.g., 3.11 to avoid Python 3.13 issues)
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure Telegram libs like `python-telegram-bot` are in requirements.txt

      - name: Run main.py
        env:  # Inject secrets as environment variables
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
