name: Run Python Script Every 30 Minutes
on:
  schedule:
    # Runs every 30 minutes (e.g., 12:00, 12:30, 1:00, etc.)
    - cron: "*/30 * * * *"

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # Replace with your Python version (e.g., 3.10)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py
        run: python main.py
